trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
    npm --prefix server ci
    npm --prefix client ci
  displayName: 'Install Dependencies'
- script: npm run build
  displayName: 'Build'
- script: |
    /usr/bin/zip -r $(Build.ArtifactStagingDirectory)/CRON-$(Build.BuildId).zip . -i $(Build.ArtifactStagingDirectory)/server $(Build.ArtifactStagingDirectory)/static
  displayName: 'Zip'
- task: PublishBuildArtifacts@1
  displayName: 
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/CRON-$(Build.BuildId).zip'
    ArtifactName: 'CRON'
    publishLocation: 'Container'  
