name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install and build
        run: |
          npm ci
          npm ci --prefix server
          npm ci --prefix client
          npm run build
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          rm: true
          source: "server/,static/"
          target: "cron-server"
      - name: start server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          script: |
            tmux kill-session -t cron-server
#            tmux new-session -c cron-server -d -s "cron-server" sudo PORT=2000 NODE_ENV=production SECRET=${{ secrets.SECRET }} DB_HOST=${{ secrets.DB_HOST }} USER_EMAIL=${{ secrets.USER_EMAIL }} USER_PASSWORD=${{ secrets.USER_PASSWORD }} node server/index.js
