name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'client/**/*'
      - 'server/**/*'
      - '.github/workflows/ssh_deploy.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build
        run: |
          npm ci --prefix server
          npm ci --prefix client
          npm run build
      - name: copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          rm: true
          source: "server/,static/"
          target: "cron-server"
      - name: start server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          script: |
            cd cron-server
            sudo pm2 stop cron-server
            sudo PORT=2000 NODE_ENV=production SECRET=${{ secrets.SECRET }} DB_HOST=${{ secrets.DB_HOST }} USER_EMAIL=${{ secrets.USER_EMAIL }} USER_PASSWORD=${{ secrets.USER_PASSWORD }} pm2 start server/index.js --name cron-server
